name: taskmanager
description: An Offshorly mini-project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.2
  json_annotation: ^4.8.1
  path_provider: ^2.1.0
  repository:
     path: packages/repository
  sqlite3_flutter_libs: ^0.5.15

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0+1

# dependency_overrides:
#   test_api: ^0.4.17

flutter:
  uses-material-design: true

assets:
 - assets/