name: database
description: Database package for task management app.
version: 0.0.1
homepage: null

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  drift: ^2.11.0
  flutter:
    sdk: flutter
  path: ^1.8.3
  path_provider: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.6
  drift_dev: ^2.11.0
  very_good_analysis: ^5.0.0+1

flutter: null
